### ISSUE TITLE
Add filter by score

### ISSUE THREAD

**Issue by adf-ncgr** [ncgr/lis_sequence_search#2]
e-values are a good first filter, but once they get low enough to be reported as zero, there is no finer level filtering that can be done using that property of a set of hits. Adding bit score filtering would help.

**Comment by hunzinker** [comment]
Added filter by bit score in feature branch.

https://github.com/ncgr/lis_sequence_search/commit/f131afc189826a3c05f81079a3a15b912454144c

**Comment by adf-ncgr** [comment]
When a numeric filter is in place, and a "canned" filter is newly selected, the numeric filter is ignored
in the resultant.

**Comment by hunzinker** [comment]
Updated to retain filter values when a canned filter is selected.

https://github.com/ncgr/lis_sequence_search/commit/9929d069aae6e55abd8cd1661a7616fbd986928a

**Comment by hunzinker** [comment]
Moved filter into master. Released under v0.3.0.
