### ISSUE TITLE
dual partition/table view for innovative traditionalism and traditional innovation

### ISSUE THREAD

**Issue by adf-ncgr** [ncgr/lis_sequence_search#5]
The subject of whether the partition view or the tabular view should be presented as the default is contentious. On the other hand, strong arguments can be made that neither view by itself tells the complete story. Presenting the two together in a split pane (or similar) context, in which both were simultaneously updated with changes to the model effected by filter applications may be a way forward.

**Comment by hunzinker** [comment]
It's in master!
