### ISSUE TITLE
table in dual view does not appear initially when one selected algorithm has no queries of the appropriate type

### ISSUE THREAD

**Issue by adf-ncgr** [ncgr/lis_sequence_search#7]
for example, if I have a few protein sequences, and request a search with 
blastp and tblastn (correct) and also blastx (incorrect-o!), the initial view is
partition only, no table. This is not corrected upon a refresh, but the table 
does appear upon any interaction with the partition or filters.

not a big deal, but since you're a perfectionist...

**Comment by hunzinker** [comment]
Well aware. That is the last bug on my list!

**Comment by hunzinker** [comment]
Fixed and in master.
