### ISSUE TITLE
archaic browser users not properly chastened!

### ISSUE THREAD

**Issue by adf-ncgr** [ncgr/lis_sequence_search#9]

**Comment by hunzinker** [comment]
I'm unable to reproduce this by switching my user agent to IE < 9 in chrome. Need to double check with an actual IE browser.

**Comment by hunzinker** [comment]
This issue is due to two things:

1) Compressed / minified nature of JS in the Rails asset pipeline.
2) IE < 9 errors out when attempting to load d3.js failing to render warning message.

Temporary fix:

Obtrusively warn IE < 9 users (i.e. remove the message from assets and place in the layout).

**Comment by hunzinker** [comment]
It's in master.
